package signals

import "database/sql"

type Signals struct {
	Id                         int
	Date                       string            `json:"date"`
	O2_slev                    sql.Null[float64] `json:"o2_slev"`
	O2_sprav                   sql.Null[float64] `json:"o2_sprav"`
	Q_gaz                      sql.Null[float64] `json:"q_gaz"`
	T_para_nitk_a              sql.Null[float64] `json:"t_para_nitk_a"`
	T_para_nitk_b              sql.Null[float64] `json:"t_para_nitk_b"`
	P_para                     sql.Null[float64] `json:"p_para"`
	Q_per_par                  sql.Null[float64] `json:"q_per_par"`
	Q_pit_voda                 sql.Null[float64] `json:"q_pit_voda"`
	T_vozdh_posl_rvpa          sql.Null[float64] `json:"t_vozdh_posl_rvpa"`
	T_vozdh_posl_rvpb          sql.Null[float64] `json:"t_vozdh_posl_rvpb"`
	T_vozdh_posl_tvp_slev      sql.Null[float64] `json:"t_vozdh_posl_tvp_slev"`
	T_vozdh_posl_tvp_sprav     sql.Null[float64] `json:"t_vozdh_posl_tvp_sprav"`
	T_posle_ekonomiz_slev      sql.Null[float64] `json:"t_posle_ekonomiz_slev"`
	T_posle_ekonomiz_sprav     sql.Null[float64] `json:"t_posle_ekonomiz_sprav"`
	T_dym_zarvp_slev           sql.Null[float64] `json:"t_dym_zarvp_slev"`
	T_dym_zarvp_sprav          sql.Null[float64] `json:"t_dym_zarvp_sprav"`
	T_dym_zatvp_slev           sql.Null[float64] `json:"t_dym_zatvp_slev"`
	T_dym_zatvp_sprav          sql.Null[float64] `json:"t_dym_zatvp_sprav"`
	T_pitvod_kotl              sql.Null[float64] `json:"t_pitvod_kotl"`
	T_uhodgaz_ventur1          sql.Null[float64] `json:"t_uhodgaz_ventur1"`
	T_uhodgaz_ventur2          sql.Null[float64] `json:"t_uhodgaz_ventur2"`
	T_mazut                    sql.Null[float64] `json:"t_mazut"`
	T_uhodgaz_ventur3          sql.Null[float64] `json:"t_uhodgaz_ventur3"`
	T_uhodgaz_ventur4          sql.Null[float64] `json:"t_uhodgaz_ventur4"`
	T_kontensat_sbor           sql.Null[float64] `json:"t_kontensat_sbor"`
	T_kontensat_vihkollect     sql.Null[float64] `json:"t_kontensat_vihkollect"`
	T_vod_kollect_slev         sql.Null[float64] `json:"t_vod_kollect_slev"`
	T_vod_kollect_sprav        sql.Null[float64] `json:"t_vod_kollect_sprav"`
	T_gaz_dsa                  sql.Null[float64] `json:"t_gaz_dsa"`
	T_gaz_dsb                  sql.Null[float64] `json:"t_gaz_dsb"`
	T_vozdh_pered_rvpa         sql.Null[float64] `json:"t_vozdh_pered_rvpa"`
	T_vozdh_pered_rvpb         sql.Null[float64] `json:"t_vozdh_pered_rvpb"`
	T_vozdh_pered_tvpslev      sql.Null[float64] `json:"t_vozdh_pered_tvpslev"`
	T_vozdh_pered_tvpsprav     sql.Null[float64] `json:"t_vozdh_pered_tvpsprav"`
	H_baraban_slev             sql.Null[float64] `json:"h_baraban_slev"`
	H_baraban_sprav            sql.Null[float64] `json:"h_baraban_sprav"`
	P_par_do_sk                sql.Null[float64] `json:"p_par_do_sk"`
	Q_par                      sql.Null[float64] `json:"q_par"`
	T_par_posle_sk             sql.Null[float64] `json:"t_par_posle_sk"`
	Vakum                      sql.Null[float64] `json:"vakum"`
	T_par_psg1_prov1           sql.Null[float64] `json:"t_par_psg1_prov1"`
	T_par_psg1_prov2           sql.Null[float64] `json:"t_par_psg1_prov2"`
	T_par_psg2                 sql.Null[float64] `json:"t_par_psg2"`
	T_vod_do_psg1              sql.Null[float64] `json:"t_vod_do_psg1"`
	T_vod_posle_psg1           sql.Null[float64] `json:"t_vod_posle_psg1"`
	T_vod_vihod_psg12          sql.Null[float64] `json:"t_vod_vihod_psg12"`
	T_par_posle_ou1            sql.Null[float64] `json:"t_par_posle_ou1"`
	T_par_posle_ou2            sql.Null[float64] `json:"t_par_posle_ou2"`
	T_kondesat_do_kn           sql.Null[float64] `json:"t_kondesat_do_kn"`
	T_cirk_vod_posle_kondensat sql.Null[float64] `json:"t_cirk_vod_posle_kondensat"`
	T_cirk_vod_do_kondensat    sql.Null[float64] `json:"t_cirk_vod_do_kondensat"`
	T_par_cnd_sprav            sql.Null[float64] `json:"t_par_cnd_sprav"`
	T_par_cnd_slev             sql.Null[float64] `json:"t_par_cnd_slev"`
	T_par_uplotn_kollect       sql.Null[float64] `json:"t_par_uplotn_kollect"`
	T_kondest_posle_pnd4       sql.Null[float64] `json:"t_kondest_posle_pnd4"`
	T_vod_obvod_pvd7           sql.Null[float64] `json:"t_vod_obvod_pvd7"`
	T_par_pered_pn130          sql.Null[float64] `json:"t_par_pered_pn130"`
	T_vod_posle_pvd7           sql.Null[float64] `json:"t_vod_posle_pvd7"`
	P_par_k_psg1               sql.Null[float64] `json:"p_par_k_psg1"`
	P_par_k_psg2               sql.Null[float64] `json:"p_par_k_psg2"`
	Akt_stal_vozb_paz_7        sql.Null[float64] `json:"akt_stal_vozb_paz_7"`
	Akt_stal_vozb_paz_21       sql.Null[float64] `json:"akt_stal_vozb_paz_21"`
	Akt_stal_vozb_paz_36       sql.Null[float64] `json:"akt_stal_vozb_paz_36"`
	Akt_stal_vozb_paz_50       sql.Null[float64] `json:"akt_stal_vozb_paz_50"`
	Akt_stal_vozb_paz_64       sql.Null[float64] `json:"akt_stal_vozb_paz_64"`
	Akt_stal_vozb_paz_77       sql.Null[float64] `json:"akt_stal_vozb_paz_77"`
	Akt_stal_vozb_paz_3g7      sql.Null[float64] `json:"akt_stal_vozb_paz_3g7"`
	Akt_stal_vozb_paz_25g10    sql.Null[float64] `json:"akt_stal_vozb_paz_25g10"`
	Akt_stal_vozb_paz_44g12    sql.Null[float64] `json:"akt_stal_vozb_paz_44g12"`
	Akt_stal_vozb_paz_3g13     sql.Null[float64] `json:"akt_stal_vozb_paz_3g13"`
	Akt_stal_vozb_paz_25g16    sql.Null[float64] `json:"akt_stal_vozb_paz_25g16"`
	Akt_stal_vozb_paz_44g18    sql.Null[float64] `json:"akt_stal_vozb_paz_44g18"`
	T_vod_sobstv_nuzht         sql.Null[float64] `json:"t_vod_sobstv_nuzht"`
	T_vod_glav_korp_truba1     sql.Null[float64] `json:"t_vod_glav_korp_truba1"`
	T_vod_glav_korp_truba2     sql.Null[float64] `json:"t_vod_glav_korp_truba2"`
	T_vod_za_psn1              sql.Null[float64] `json:"t_vod_za_psn1"`
	T_vod_za_psn2              sql.Null[float64] `json:"t_vod_za_psn2"`
}
